version: 2
jobs:
  build:
    machine: true
    steps:
      # fix for local builds https://github.com/CircleCI-Public/circleci-cli/issues/281
      - run: |
          if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
            echo "fixing local build ---------------------------------------------"
            git clone $CIRCLE_REPOSITORY_URL /tmp/_circleci_local_build_repo
          fi
      - checkout
      - run: echo "hello"
      # - run: node --version
      - run: docker info
      - run: npm install
      - run: npm test -- -v
      - run: npm run report-coverage
